/**
 * Seed dataset for demo mode.
 *
 * IDs are 24-character hex strings so they are interchangeable with MongoDB
 * ObjectIds — the same data can be loaded into a real database with
 * `npm run seed` without any transformation.
 *
 * Dates are generated relative to "now" at module load so the demo always has
 * travels departing next week and deadlines that have not already passed.
 */

const DAY = 24 * 60 * 60 * 1000;
const now = Date.now();
const daysFromNow = (n) => new Date(now + n * DAY);
const daysAgo = (n) => new Date(now - n * DAY);

// Coordinates power the real distance calculation in the matching engine.
export const CITIES = {
  'New York': { country: 'United States', lat: 40.7128, lon: -74.006 },
  Boston: { country: 'United States', lat: 42.3601, lon: -71.0589 },
  'San Francisco': { country: 'United States', lat: 37.7749, lon: -122.4194 },
  Chicago: { country: 'United States', lat: 41.8781, lon: -87.6298 },
  London: { country: 'United Kingdom', lat: 51.5074, lon: -0.1278 },
  Manchester: { country: 'United Kingdom', lat: 53.4808, lon: -2.2426 },
  Paris: { country: 'France', lat: 48.8566, lon: 2.3522 },
  Madrid: { country: 'Spain', lat: 40.4168, lon: -3.7038 },
  Berlin: { country: 'Germany', lat: 52.52, lon: 13.405 },
  Lagos: { country: 'Nigeria', lat: 6.5244, lon: 3.3792 },
  Accra: { country: 'Ghana', lat: 5.6037, lon: -0.187 },
  Nairobi: { country: 'Kenya', lat: -1.2921, lon: 36.8219 },
  'Addis Ababa': { country: 'Ethiopia', lat: 9.032, lon: 38.7469 },
  Dubai: { country: 'United Arab Emirates', lat: 25.2048, lon: 55.2708 },
  Mumbai: { country: 'India', lat: 19.076, lon: 72.8777 },
  Toronto: { country: 'Canada', lat: 43.6532, lon: -79.3832 },
};

export const CITY_NAMES = Object.keys(CITIES).sort();

const place = (city) => ({
  city,
  country: CITIES[city].country,
  coordinates: { latitude: CITIES[city].lat, longitude: CITIES[city].lon },
});

/** The signed-in user in demo mode. */
export const DEMO_USER_ID = '652f1a0000000000000000a1';

export const users = [
  {
    _id: DEMO_USER_ID,
    auth0Id: 'demo|calvin',
    email: 'calvin@parceflyte.dev',
    firstName: 'Calvin',
    lastName: 'Andoh',
    phoneNumber: '+1 415 555 0142',
    dateOfBirth: new Date('1994-04-11'),
    avatarColor: '#6366f1',
    address: {
      street: '18 Mission St',
      city: 'San Francisco',
      state: 'CA',
      country: 'United States',
      postalCode: '94105',
    },
    kycStatus: 'verified',
    roles: ['sender', 'carrier', 'admin'],
    rating: { average: 4.8, totalReviews: 24, completedDeliveries: 26, successfulDeliveries: 25 },
    paymentMethods: [{ type: 'stripe', last4: '4242', isDefault: true }],
    isActive: true,
    createdAt: daysAgo(420),
    updatedAt: daysAgo(3),
  },
  {
    _id: '652f1a0000000000000000a2',
    auth0Id: 'demo|amara',
    email: 'amara.okafor@example.com',
    firstName: 'Amara',
    lastName: 'Okafor',
    phoneNumber: '+44 20 7946 0812',
    dateOfBirth: new Date('1991-09-02'),
    avatarColor: '#ec4899',
    address: { city: 'London', country: 'United Kingdom', postalCode: 'E1 6AN' },
    kycStatus: 'verified',
    roles: ['carrier'],
    rating: { average: 4.9, totalReviews: 41, completedDeliveries: 43, successfulDeliveries: 43 },
    isActive: true,
    createdAt: daysAgo(610),
    updatedAt: daysAgo(11),
  },
  {
    _id: '652f1a0000000000000000a3',
    auth0Id: 'demo|luis',
    email: 'luis.moreno@example.com',
    firstName: 'Luis',
    lastName: 'Moreno',
    phoneNumber: '+34 91 123 4567',
    dateOfBirth: new Date('1988-01-23'),
    avatarColor: '#f59e0b',
    address: { city: 'Madrid', country: 'Spain', postalCode: '28013' },
    kycStatus: 'verified',
    roles: ['carrier', 'sender'],
    rating: { average: 4.6, totalReviews: 12, completedDeliveries: 13, successfulDeliveries: 12 },
    isActive: true,
    createdAt: daysAgo(300),
    updatedAt: daysAgo(20),
  },
  {
    _id: '652f1a0000000000000000a4',
    auth0Id: 'demo|mei',
    email: 'mei.tanaka@example.com',
    firstName: 'Mei',
    lastName: 'Tanaka',
    phoneNumber: '+1 617 555 0199',
    dateOfBirth: new Date('1996-06-30'),
    avatarColor: '#14b8a6',
    address: { city: 'Boston', country: 'United States', postalCode: '02108' },
    kycStatus: 'verified',
    roles: ['carrier'],
    rating: { average: 4.4, totalReviews: 7, completedDeliveries: 8, successfulDeliveries: 7 },
    isActive: true,
    createdAt: daysAgo(150),
    updatedAt: daysAgo(5),
  },
  {
    _id: '652f1a0000000000000000a5',
    auth0Id: 'demo|kwame',
    email: 'kwame.mensah@example.com',
    firstName: 'Kwame',
    lastName: 'Mensah',
    phoneNumber: '+233 30 123 4567',
    dateOfBirth: new Date('1993-11-14'),
    avatarColor: '#8b5cf6',
    address: { city: 'Accra', country: 'Ghana' },
    kycStatus: 'pending',
    roles: ['carrier'],
    rating: { average: 0, totalReviews: 0, completedDeliveries: 0, successfulDeliveries: 0 },
    isActive: true,
    createdAt: daysAgo(12),
    updatedAt: daysAgo(2),
  },
  {
    _id: '652f1a0000000000000000a6',
    auth0Id: 'demo|sofia',
    email: 'sofia.rossi@example.com',
    firstName: 'Sofia',
    lastName: 'Rossi',
    phoneNumber: '+49 30 1234 5678',
    dateOfBirth: new Date('1990-02-17'),
    avatarColor: '#0ea5e9',
    address: { city: 'Berlin', country: 'Germany' },
    kycStatus: 'verified',
    roles: ['carrier'],
    rating: { average: 5.0, totalReviews: 18, completedDeliveries: 18, successfulDeliveries: 18 },
    isActive: true,
    createdAt: daysAgo(500),
    updatedAt: daysAgo(9),
  },
  {
    _id: '652f1a0000000000000000a7',
    auth0Id: 'demo|priya',
    email: 'priya.sharma@example.com',
    firstName: 'Priya',
    lastName: 'Sharma',
    phoneNumber: '+971 4 123 4567',
    dateOfBirth: new Date('1992-08-08'),
    avatarColor: '#f43f5e',
    address: { city: 'Dubai', country: 'United Arab Emirates' },
    kycStatus: 'pending',
    roles: ['carrier', 'sender'],
    rating: { average: 4.2, totalReviews: 5, completedDeliveries: 6, successfulDeliveries: 5 },
    isActive: true,
    createdAt: daysAgo(40),
    updatedAt: daysAgo(1),
  },
  {
    _id: '652f1a0000000000000000ad',
    auth0Id: 'demo|admin',
    email: 'admin@parceflyte.dev',
    firstName: 'Ada',
    lastName: 'Reyes',
    phoneNumber: '+1 415 555 0100',
    dateOfBirth: new Date('1985-03-05'),
    avatarColor: '#334155',
    address: { city: 'San Francisco', country: 'United States' },
    kycStatus: 'verified',
    roles: ['admin'],
    rating: { average: 0, totalReviews: 0, completedDeliveries: 0, successfulDeliveries: 0 },
    isActive: true,
    createdAt: daysAgo(800),
    updatedAt: daysAgo(30),
  },
];

export const travels = [
  {
    _id: '652f1b0000000000000000b1',
    carrierId: '652f1a0000000000000000a2',
    departureLocation: place('London'),
    arrivalLocation: place('Lagos'),
    travelMode: 'air',
    transportDetails: { type: 'plane', carrier: 'British Airways', reference: 'BA075' },
    departureDate: daysFromNow(6),
    arrivalDate: daysFromNow(6),
    availableCapacity: { weight: 12, volume: 40 },
    baseDeliveryFee: 45,
    currency: 'USD',
    status: 'confirmed',
    verificationMethod: 'document_upload',
    notes: 'Happy to take documents and small electronics. No liquids.',
    createdAt: daysAgo(8),
    updatedAt: daysAgo(2),
  },
  {
    _id: '652f1b0000000000000000b2',
    carrierId: '652f1a0000000000000000a3',
    departureLocation: place('Madrid'),
    arrivalLocation: place('Accra'),
    travelMode: 'air',
    transportDetails: { type: 'plane', carrier: 'Iberia', reference: 'IB3117' },
    departureDate: daysFromNow(11),
    arrivalDate: daysFromNow(11),
    availableCapacity: { weight: 8, volume: 25 },
    baseDeliveryFee: 40,
    currency: 'USD',
    status: 'planned',
    verificationMethod: 'manual',
    notes: 'Two spare kilos in hand luggage, more in hold if booked early.',
    createdAt: daysAgo(5),
    updatedAt: daysAgo(5),
  },
  {
    _id: '652f1b0000000000000000b3',
    carrierId: '652f1a0000000000000000a4',
    departureLocation: place('Boston'),
    arrivalLocation: place('London'),
    travelMode: 'air',
    transportDetails: { type: 'plane', carrier: 'Virgin Atlantic', reference: 'VS012' },
    departureDate: daysFromNow(4),
    arrivalDate: daysFromNow(5),
    availableCapacity: { weight: 6, volume: 18 },
    baseDeliveryFee: 38,
    currency: 'USD',
    status: 'confirmed',
    verificationMethod: 'document_upload',
    notes: 'Direct overnight flight, can meet near South Station before departure.',
    createdAt: daysAgo(14),
    updatedAt: daysAgo(1),
  },
  {
    _id: '652f1b0000000000000000b4',
    carrierId: '652f1a0000000000000000a6',
    departureLocation: place('Berlin'),
    arrivalLocation: place('Nairobi'),
    travelMode: 'air',
    transportDetails: { type: 'plane', carrier: 'Lufthansa', reference: 'LH590' },
    departureDate: daysFromNow(9),
    arrivalDate: daysFromNow(10),
    availableCapacity: { weight: 15, volume: 55 },
    baseDeliveryFee: 48,
    currency: 'USD',
    status: 'confirmed',
    verificationMethod: 'third_party',
    notes: 'Frequent flyer with extra baggage allowance. Fragile items welcome.',
    createdAt: daysAgo(21),
    updatedAt: daysAgo(4),
  },
  {
    _id: '652f1b0000000000000000b5',
    carrierId: '652f1a0000000000000000a7',
    departureLocation: place('Dubai'),
    arrivalLocation: place('Mumbai'),
    travelMode: 'air',
    transportDetails: { type: 'plane', carrier: 'Emirates', reference: 'EK500' },
    departureDate: daysFromNow(3),
    arrivalDate: daysFromNow(3),
    availableCapacity: { weight: 10, volume: 30 },
    baseDeliveryFee: 38,
    currency: 'USD',
    status: 'confirmed',
    verificationMethod: 'manual',
    notes: 'Weekly commute, very reliable schedule.',
    createdAt: daysAgo(30),
    updatedAt: daysAgo(6),
  },
  {
    _id: '652f1b0000000000000000b6',
    carrierId: '652f1a0000000000000000a5',
    departureLocation: place('Accra'),
    arrivalLocation: place('London'),
    travelMode: 'air',
    transportDetails: { type: 'plane', carrier: 'Ghana Airways', reference: 'GH200' },
    departureDate: daysFromNow(16),
    arrivalDate: daysFromNow(16),
    availableCapacity: { weight: 20, volume: 60 },
    baseDeliveryFee: 44,
    currency: 'USD',
    status: 'planned',
    verificationMethod: 'manual',
    notes: 'New to the platform — verification in progress.',
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
  },
  {
    _id: '652f1b0000000000000000b7',
    carrierId: '652f1a0000000000000000a2',
    departureLocation: place('London'),
    arrivalLocation: place('New York'),
    travelMode: 'air',
    transportDetails: { type: 'plane', carrier: 'British Airways', reference: 'BA117' },
    departureDate: daysFromNow(20),
    arrivalDate: daysFromNow(20),
    availableCapacity: { weight: 9, volume: 28 },
    baseDeliveryFee: 42,
    currency: 'USD',
    status: 'planned',
    verificationMethod: 'document_upload',
    notes: 'Regular route, twice a month.',
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
  },
  {
    _id: '652f1b0000000000000000b8',
    carrierId: DEMO_USER_ID,
    departureLocation: place('San Francisco'),
    arrivalLocation: place('Toronto'),
    travelMode: 'air',
    transportDetails: { type: 'plane', carrier: 'Air Canada', reference: 'AC756' },
    departureDate: daysFromNow(13),
    arrivalDate: daysFromNow(13),
    availableCapacity: { weight: 7, volume: 22 },
    baseDeliveryFee: 36,
    currency: 'USD',
    status: 'planned',
    verificationMethod: 'manual',
    notes: 'Visiting family — happy to carry documents or small gifts.',
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    _id: '652f1b0000000000000000b9',
    carrierId: '652f1a0000000000000000a4',
    departureLocation: place('Chicago'),
    arrivalLocation: place('Paris'),
    travelMode: 'air',
    transportDetails: { type: 'plane', carrier: 'Air France', reference: 'AF137' },
    departureDate: daysFromNow(8),
    arrivalDate: daysFromNow(9),
    availableCapacity: { weight: 5, volume: 15 },
    baseDeliveryFee: 40,
    currency: 'USD',
    status: 'confirmed',
    verificationMethod: 'document_upload',
    notes: 'Small items only please.',
    createdAt: daysAgo(6),
    updatedAt: daysAgo(6),
  },
  {
    _id: '652f1b000000000000000b11',
    carrierId: '652f1a0000000000000000a6',
    departureLocation: place('London'),
    arrivalLocation: place('Lagos'),
    travelMode: 'air',
    transportDetails: { type: 'plane', carrier: 'Virgin Atlantic', reference: 'VS411' },
    departureDate: daysFromNow(8),
    arrivalDate: daysFromNow(8),
    availableCapacity: { weight: 4, volume: 14 },
    baseDeliveryFee: 32,
    currency: 'USD',
    status: 'confirmed',
    verificationMethod: 'third_party',
    notes: 'Small parcels only, but I am cheap and reliable.',
    createdAt: daysAgo(4),
    updatedAt: daysAgo(4),
  },
  {
    _id: '652f1b000000000000000b12',
    carrierId: '652f1a0000000000000000a3',
    departureLocation: place('London'),
    arrivalLocation: place('Lagos'),
    travelMode: 'air',
    transportDetails: { type: 'plane', carrier: 'Air Peace', reference: 'P47100' },
    departureDate: daysFromNow(12),
    arrivalDate: daysFromNow(12),
    availableCapacity: { weight: 22, volume: 70 },
    baseDeliveryFee: 41,
    currency: 'USD',
    status: 'planned',
    verificationMethod: 'document_upload',
    notes: 'Checked bag mostly empty — happy to take something bulky.',
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
  },
  {
    _id: '652f1b000000000000000b13',
    carrierId: '652f1a0000000000000000a6',
    departureLocation: place('Boston'),
    arrivalLocation: place('London'),
    travelMode: 'air',
    transportDetails: { type: 'plane', carrier: 'Delta', reference: 'DL058' },
    departureDate: daysFromNow(5),
    arrivalDate: daysFromNow(6),
    availableCapacity: { weight: 3, volume: 9 },
    baseDeliveryFee: 30,
    currency: 'USD',
    status: 'confirmed',
    verificationMethod: 'third_party',
    notes: 'Cabin bag only — documents and small electronics.',
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
  },
  {
    _id: '652f1b000000000000000b10',
    carrierId: '652f1a0000000000000000a6',
    departureLocation: place('Manchester'),
    arrivalLocation: place('Addis Ababa'),
    travelMode: 'air',
    transportDetails: { type: 'plane', carrier: 'Ethiopian Airlines', reference: 'ET711' },
    departureDate: daysFromNow(25),
    arrivalDate: daysFromNow(26),
    availableCapacity: { weight: 18, volume: 50 },
    baseDeliveryFee: 46,
    currency: 'USD',
    status: 'planned',
    verificationMethod: 'third_party',
    notes: 'Large capacity, can handle bulky but light items.',
    createdAt: daysAgo(4),
    updatedAt: daysAgo(4),
  },
];

export const parcels = [
  {
    _id: '652f1c0000000000000000c1',
    senderId: DEMO_USER_ID,
    title: 'Birthday gift box',
    description: 'Wrapped gift — a wool scarf and a photo book.',
    origin: place('London'),
    weight: 2.5,
    volume: 12,
    dimensions: { length: 35, width: 25, height: 14, unit: 'cm' },
    declaredValue: 320,
    category: 'clothing',
    specialHandling: ['fragile'],
    recipient: {
      name: 'Ngozi Okafor',
      phone: '+234 1 234 5678',
      email: 'ngozi@example.com',
      address: place('Lagos'),
    },
    deliveryDeadline: daysFromNow(14),
    preferredDeliveryTime: 'anytime',
    status: 'pending',
    paymentStatus: 'pending',
    insuranceRequired: true,
    insuranceAmount: 12,
    trackingHistory: [{ status: 'created', timestamp: daysAgo(2), note: 'Parcel listed' }],
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
  },
  {
    _id: '652f1c0000000000000000c2',
    senderId: DEMO_USER_ID,
    title: 'Replacement laptop charger',
    description: 'Sealed 96W USB-C charger, still boxed.',
    origin: place('Boston'),
    weight: 0.8,
    volume: 3,
    dimensions: { length: 18, width: 12, height: 6, unit: 'cm' },
    declaredValue: 95,
    category: 'electronics',
    specialHandling: ['signature_required'],
    recipient: {
      name: 'Tom Whitfield',
      phone: '+44 7700 900123',
      email: 'tom@example.com',
      address: place('London'),
    },
    deliveryDeadline: daysFromNow(9),
    preferredDeliveryTime: 'afternoon',
    status: 'matched',
    matchedCarrierId: '652f1a0000000000000000a4',
    paymentStatus: 'paid',
    insuranceRequired: false,
    trackingHistory: [
      { status: 'created', timestamp: daysAgo(7), note: 'Parcel listed' },
      { status: 'matched', timestamp: daysAgo(1), note: 'Matched with Mei Tanaka' },
    ],
    createdAt: daysAgo(7),
    updatedAt: daysAgo(1),
  },
  {
    _id: '652f1c0000000000000000c3',
    senderId: '652f1a0000000000000000a3',
    title: 'University transcripts',
    description: 'Sealed envelope from the registrar. Time sensitive.',
    origin: place('Madrid'),
    weight: 0.3,
    volume: 1,
    dimensions: { length: 32, width: 23, height: 2, unit: 'cm' },
    declaredValue: 60,
    category: 'documents',
    specialHandling: ['urgent', 'signature_required'],
    recipient: {
      name: 'Yaw Boateng',
      phone: '+233 24 123 4567',
      address: place('Accra'),
    },
    deliveryDeadline: daysFromNow(13),
    preferredDeliveryTime: 'morning',
    status: 'pending',
    paymentStatus: 'pending',
    insuranceRequired: false,
    trackingHistory: [{ status: 'created', timestamp: daysAgo(4), note: 'Parcel listed' }],
    createdAt: daysAgo(4),
    updatedAt: daysAgo(4),
  },
  {
    _id: '652f1c0000000000000000c4',
    senderId: '652f1a0000000000000000a7',
    title: 'Camera lens',
    description: '50mm prime lens in a padded case.',
    origin: place('Dubai'),
    weight: 1.2,
    volume: 5,
    dimensions: { length: 15, width: 15, height: 12, unit: 'cm' },
    declaredValue: 480,
    category: 'electronics',
    specialHandling: ['fragile', 'photo_proof'],
    recipient: {
      name: 'Rahul Desai',
      phone: '+91 22 1234 5678',
      address: place('Mumbai'),
    },
    deliveryDeadline: daysFromNow(6),
    preferredDeliveryTime: 'evening',
    status: 'pending',
    paymentStatus: 'pending',
    insuranceRequired: true,
    insuranceAmount: 24,
    trackingHistory: [{ status: 'created', timestamp: daysAgo(1), note: 'Parcel listed' }],
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    _id: '652f1c0000000000000000c5',
    senderId: DEMO_USER_ID,
    title: 'Handmade ceramics',
    description: 'Two small bowls, individually bubble wrapped.',
    origin: place('San Francisco'),
    weight: 1.9,
    volume: 9,
    dimensions: { length: 28, width: 22, height: 16, unit: 'cm' },
    declaredValue: 140,
    category: 'other',
    specialHandling: ['fragile'],
    recipient: {
      name: 'Grace Lam',
      phone: '+1 416 555 0177',
      address: place('Toronto'),
    },
    deliveryDeadline: daysFromNow(30),
    preferredDeliveryTime: 'anytime',
    status: 'delivered',
    matchedCarrierId: '652f1a0000000000000000a2',
    paymentStatus: 'released',
    insuranceRequired: false,
    trackingHistory: [
      { status: 'created', timestamp: daysAgo(40), note: 'Parcel listed' },
      { status: 'matched', timestamp: daysAgo(36), note: 'Matched with Amara Okafor' },
      { status: 'picked_up', timestamp: daysAgo(31), note: 'Collected in San Francisco' },
      { status: 'in_transit', timestamp: daysAgo(30), note: 'In the air' },
      { status: 'delivered', timestamp: daysAgo(29), note: 'Signed for by Grace Lam' },
    ],
    createdAt: daysAgo(40),
    updatedAt: daysAgo(29),
  },
];

export const matches = [
  {
    _id: '652f1d0000000000000000d1',
    parcelId: '652f1c0000000000000000c1',
    travelId: '652f1b0000000000000000b1',
    senderId: DEMO_USER_ID,
    carrierId: '652f1a0000000000000000a2',
    status: 'proposed',
    matchScore: 84,
    negotiation: {
      initialFee: 45,
      proposedFee: 38,
      finalFee: null,
      currency: 'USD',
      negotiationHistory: [
        {
          proposedBy: DEMO_USER_ID,
          amount: 34,
          message: 'Would you consider $34? It is a light parcel and I can drop it at the airport.',
          timestamp: daysAgo(1),
        },
        {
          proposedBy: '652f1a0000000000000000a2',
          amount: 38,
          message: 'I can do $38 given it is marked fragile — happy to meet you at Heathrow.',
          timestamp: daysAgo(0.5),
        },
      ],
    },
    agreement: {
      pickupLocation: 'London Heathrow, Terminal 5',
      pickupDate: daysFromNow(6),
      deliveryLocation: 'Lagos, Ikeja',
      deliveryDate: daysFromNow(7),
      specialInstructions: 'Please keep upright.',
      insuranceRequired: true,
      insuranceAmount: 12,
    },
    messages: [],
    expiresAt: daysFromNow(4),
    createdAt: daysAgo(1),
    updatedAt: daysAgo(0.5),
  },
  {
    _id: '652f1d0000000000000000d2',
    parcelId: '652f1c0000000000000000c2',
    travelId: '652f1b0000000000000000b3',
    senderId: DEMO_USER_ID,
    carrierId: '652f1a0000000000000000a4',
    status: 'accepted',
    matchScore: 86,
    negotiation: {
      initialFee: 38,
      proposedFee: 34,
      finalFee: 34,
      currency: 'USD',
      negotiationHistory: [
        {
          proposedBy: DEMO_USER_ID,
          amount: 34,
          message: 'It is only 800g — would $34 work?',
          timestamp: daysAgo(2),
        },
      ],
    },
    agreement: {
      pickupLocation: 'Boston, South Station',
      pickupDate: daysFromNow(4),
      deliveryLocation: 'London, Shoreditch',
      deliveryDate: daysFromNow(5),
      specialInstructions: 'Recipient will sign on delivery.',
      insuranceRequired: false,
    },
    messages: [],
    acceptedAt: daysAgo(1),
    expiresAt: daysFromNow(3),
    createdAt: daysAgo(2),
    updatedAt: daysAgo(1),
  },
  {
    _id: '652f1d0000000000000000d3',
    parcelId: '652f1c0000000000000000c3',
    travelId: '652f1b0000000000000000b2',
    senderId: '652f1a0000000000000000a3',
    carrierId: '652f1a0000000000000000a3',
    status: 'proposed',
    matchScore: 78,
    negotiation: {
      initialFee: 40,
      proposedFee: null,
      finalFee: null,
      currency: 'USD',
      negotiationHistory: [],
    },
    agreement: {
      pickupLocation: 'Madrid, Barajas T4',
      pickupDate: daysFromNow(11),
      deliveryLocation: 'Accra, Osu',
      deliveryDate: daysFromNow(12),
      insuranceRequired: false,
    },
    messages: [],
    expiresAt: daysFromNow(7),
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
  },
  {
    _id: '652f1d0000000000000000d4',
    parcelId: '652f1c0000000000000000c5',
    travelId: '652f1b0000000000000000b7',
    senderId: DEMO_USER_ID,
    carrierId: '652f1a0000000000000000a2',
    status: 'accepted',
    matchScore: 83,
    negotiation: {
      initialFee: 36,
      proposedFee: 36,
      finalFee: 36,
      currency: 'USD',
      negotiationHistory: [],
    },
    agreement: {
      pickupLocation: 'San Francisco, Mission District',
      pickupDate: daysAgo(31),
      deliveryLocation: 'Toronto, Downtown',
      deliveryDate: daysAgo(29),
      insuranceRequired: false,
    },
    messages: [],
    acceptedAt: daysAgo(36),
    expiresAt: daysAgo(33),
    createdAt: daysAgo(37),
    updatedAt: daysAgo(29),
  },
];

export const payments = [
  {
    _id: '652f1e0000000000000000e1',
    matchId: '652f1d0000000000000000d2',
    parcelId: '652f1c0000000000000000c2',
    senderId: DEMO_USER_ID,
    carrierId: '652f1a0000000000000000a4',
    amount: 34,
    currency: 'USD',
    paymentMethod: 'stripe',
    status: 'completed',
    escrowStatus: 'funded',
    releaseCondition: 'delivery_confirmed',
    disputes: [],
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    _id: '652f1e0000000000000000e2',
    matchId: '652f1d0000000000000000d4',
    parcelId: '652f1c0000000000000000c5',
    senderId: DEMO_USER_ID,
    carrierId: '652f1a0000000000000000a2',
    amount: 36,
    currency: 'USD',
    paymentMethod: 'stripe',
    status: 'completed',
    escrowStatus: 'released',
    releaseCondition: 'delivery_confirmed',
    releasedAt: daysAgo(29),
    disputes: [],
    createdAt: daysAgo(36),
    updatedAt: daysAgo(29),
  },
];

export const ratings = [
  {
    _id: '652f1f0000000000000000f1',
    parcelId: '652f1c0000000000000000c5',
    reviewerId: DEMO_USER_ID,
    reviewedId: '652f1a0000000000000000a2',
    ratingType: 'sender_to_carrier',
    score: 5,
    review: 'Amara wrapped everything again before flying. Arrived without a scratch.',
    status: 'published',
    flags: [],
    helpfulness: [],
    createdAt: daysAgo(28),
    updatedAt: daysAgo(28),
  },
  {
    _id: '652f1f0000000000000000f2',
    parcelId: '652f1c0000000000000000c5',
    reviewerId: '652f1a0000000000000000a2',
    reviewedId: DEMO_USER_ID,
    ratingType: 'carrier_to_sender',
    score: 5,
    review: 'Clear instructions and packed properly. Would carry for Calvin again.',
    status: 'published',
    flags: [],
    helpfulness: [],
    createdAt: daysAgo(28),
    updatedAt: daysAgo(28),
  },
];

export const kyc = [
  {
    _id: '652f200000000000000000a1',
    kycId: 'KYC-2024-0001',
    userId: '652f1a0000000000000000a5',
    personalInfo: {
      firstName: 'Kwame',
      lastName: 'Mensah',
      dateOfBirth: new Date('1993-11-14'),
      nationality: 'Ghana',
      gender: 'male',
    },
    address: { currentAddress: { city: 'Accra', country: 'Ghana', street: '12 Oxford St' } },
    contactInfo: { phoneNumber: '+233 30 123 4567', email: 'kwame.mensah@example.com' },
    identityDocuments: [
      {
        documentType: 'passport',
        documentNumber: 'G1234567',
        issuingCountry: 'Ghana',
        issueDate: daysAgo(900),
        expiryDate: daysFromNow(1600),
        documentImages: [
          { type: 'front', imageUrl: '/demo/doc-front.png', uploadedAt: daysAgo(2), verificationMethod: 'ai' },
          { type: 'selfie_with_document', imageUrl: '/demo/doc-selfie.png', uploadedAt: daysAgo(2), verificationMethod: 'ai' },
        ],
        verificationStatus: 'pending',
      },
    ],
    employment: { employmentStatus: 'employed', jobTitle: 'Logistics coordinator' },
    verificationProcess: { status: 'pending', submittedAt: daysAgo(2) },
    riskAssessment: {
      riskScore: 35,
      riskLevel: 'high',
      riskFactors: ['new_user', 'international_transfers'],
      flagged: true,
    },
    compliance: {
      pepCheck: { status: 'clear', checkedAt: daysAgo(2) },
      sanctionsCheck: { status: 'clear', checkedAt: daysAgo(2) },
      amlCheck: { status: 'review', checkedAt: daysAgo(2) },
    },
    documentVerification: {
      faceMatch: { score: 0.94, passed: true },
      documentAuthenticity: { score: 0.88, passed: true },
      livenessCheck: { score: 0.91, passed: true },
    },
    communicationHistory: [],
    auditTrail: [{ action: 'submitted', timestamp: daysAgo(2), actor: '652f1a0000000000000000a5' }],
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
  },
  {
    _id: '652f200000000000000000a2',
    kycId: 'KYC-2024-0002',
    userId: '652f1a0000000000000000a7',
    personalInfo: {
      firstName: 'Priya',
      lastName: 'Sharma',
      dateOfBirth: new Date('1992-08-08'),
      nationality: 'India',
      gender: 'female',
    },
    address: { currentAddress: { city: 'Dubai', country: 'United Arab Emirates' } },
    contactInfo: { phoneNumber: '+971 4 123 4567', email: 'priya.sharma@example.com' },
    identityDocuments: [
      {
        documentType: 'national_id',
        documentNumber: 'AE998877',
        issuingCountry: 'United Arab Emirates',
        issueDate: daysAgo(1200),
        expiryDate: daysFromNow(900),
        documentImages: [
          { type: 'front', imageUrl: '/demo/doc-front.png', uploadedAt: daysAgo(1), verificationMethod: 'ai' },
          { type: 'back', imageUrl: '/demo/doc-back.png', uploadedAt: daysAgo(1), verificationMethod: 'ai' },
        ],
        verificationStatus: 'pending',
      },
    ],
    employment: { employmentStatus: 'self_employed', jobTitle: 'Consultant' },
    verificationProcess: { status: 'in_review', submittedAt: daysAgo(1) },
    riskAssessment: {
      riskScore: 15,
      riskLevel: 'low',
      riskFactors: ['international_transfers'],
      flagged: false,
    },
    compliance: {
      pepCheck: { status: 'clear', checkedAt: daysAgo(1) },
      sanctionsCheck: { status: 'clear', checkedAt: daysAgo(1) },
      amlCheck: { status: 'clear', checkedAt: daysAgo(1) },
    },
    documentVerification: {
      faceMatch: { score: 0.97, passed: true },
      documentAuthenticity: { score: 0.95, passed: true },
      livenessCheck: { score: 0.96, passed: true },
    },
    communicationHistory: [],
    auditTrail: [{ action: 'submitted', timestamp: daysAgo(1), actor: '652f1a0000000000000000a7' }],
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    _id: '652f200000000000000000a3',
    kycId: 'KYC-2024-0003',
    userId: '652f1a0000000000000000a3',
    personalInfo: {
      firstName: 'Luis',
      lastName: 'Moreno',
      dateOfBirth: new Date('1988-01-23'),
      nationality: 'Spain',
      gender: 'male',
    },
    address: { currentAddress: { city: 'Madrid', country: 'Spain' } },
    contactInfo: { phoneNumber: '+34 91 123 4567', email: 'luis.moreno@example.com' },
    identityDocuments: [
      {
        documentType: 'passport',
        documentNumber: 'ESP445566',
        issuingCountry: 'Spain',
        issueDate: daysAgo(1500),
        expiryDate: daysFromNow(2000),
        documentImages: [
          { type: 'front', imageUrl: '/demo/doc-front.png', uploadedAt: daysAgo(200), verifiedAt: daysAgo(198), verificationMethod: 'ai' },
        ],
        verificationStatus: 'verified',
      },
    ],
    employment: { employmentStatus: 'employed', jobTitle: 'Product designer' },
    verificationProcess: {
      status: 'approved',
      submittedAt: daysAgo(200),
      reviewedAt: daysAgo(198),
      approvedAt: daysAgo(198),
    },
    riskAssessment: { riskScore: 5, riskLevel: 'low', riskFactors: [], flagged: false },
    compliance: {
      pepCheck: { status: 'clear', checkedAt: daysAgo(199) },
      sanctionsCheck: { status: 'clear', checkedAt: daysAgo(199) },
      amlCheck: { status: 'clear', checkedAt: daysAgo(199) },
    },
    documentVerification: {
      faceMatch: { score: 0.99, passed: true },
      documentAuthenticity: { score: 0.98, passed: true },
      livenessCheck: { score: 0.98, passed: true },
    },
    communicationHistory: [],
    auditTrail: [
      { action: 'submitted', timestamp: daysAgo(200), actor: '652f1a0000000000000000a3' },
      { action: 'approved', timestamp: daysAgo(198), actor: '652f1a0000000000000000ad' },
    ],
    createdAt: daysAgo(200),
    updatedAt: daysAgo(198),
  },
];

/** Fresh deep copy of the whole dataset — used to seed and to reset the demo. */
export function buildSeedData() {
  return structuredClone({ users, travels, parcels, matches, payments, ratings, kyc });
}
